Set input file encoding to latin1
Without this, the encoding of strings for the output will be invalid
UTF-8. This gives errors when the file is read by various tools such as

with DuckDB:

```shell
$ duckdb -c "$(cat <<'EOF'
> SELECT DISTINCT chnm FROM 'brick/invitrodb.parquet/part-*.parquet';
> EOF
> )"
Error: Invalid Input Error: Invalid string encoding found in Parquet file: value "(\xB1)-cis-3-Methyl fentanyl hydrochloride" is not valid UTF8!
```

or with `pyarrow` when converting to `pandas`:

```
pyarrow.lib.ArrowException: Unknown error: Wrapping (�)-Bornyl acetate failed
```